# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Calle')),
                ('street_number', models.CharField(blank=True, max_length=10, verbose_name='Número exterior')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Colonia')),
                ('zip_code', models.PositiveSmallIntegerField(verbose_name='Código postal')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='Delegación/Municipio')),
                ('lat', models.FloatField(blank=True, verbose_name='Latitud')),
                ('lng', models.FloatField(blank=True, verbose_name='Longitud')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, verbose_name='Precio en MXN')),
                ('number_of_rooms', models.IntegerField(blank=True, verbose_name='Número de recámaras')),
                ('number_of_bathrooms', models.IntegerField(blank=True, verbose_name='Número de baños')),
                ('area', models.IntegerField(blank=True, verbose_name='Área en metros cuadrados')),
                ('score', models.FloatField(verbose_name='Puntuación')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.Address', verbose_name='Dirección')),
            ],
        ),
    ]
