# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20170514_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='url',
            field=models.URLField(blank=True, max_length=300, verbose_name='URL de la publicación'),
        ),
    ]
