# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Venta'), (2, 'Renta')], default=1, verbose_name='Tipo de transacción'),
            preserve_default=False,
        ),
    ]
