# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20170514_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentProperty',
            fields=[
            ],
            options={
                'verbose_name': 'Inmueble en renta',
                'verbose_name_plural': 'Inmuebles en renta',
                'proxy': True,
                'indexes': [],
            },
            bases=('properties.property',),
        ),
        migrations.CreateModel(
            name='SaleProperty',
            fields=[
            ],
            options={
                'verbose_name': 'Inmueble en venta',
                'verbose_name_plural': 'Inmuebles en venta',
                'proxy': True,
                'indexes': [],
            },
            bases=('properties.property',),
        ),
    ]
